name: "Release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  upload-artifact:
    name: Upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_TYPES: tar.gz
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

      - name: Compile
        id: compile2
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-apple-darwin
          ARCHIVE_TYPES: tar.gz
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile2.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile2.outputs.BUILT_CHECKSUM }}

      - name: Release to GitHub
        run: |
          gh release upload ${{ github.ref_name }} ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          gh release upload ${{ github.ref_name  }} ${{ steps.compile.outputs.BUILT_CHECKSUM }}
          gh release upload ${{ github.ref_name  }} ${{ steps.compile2.outputs.BUILT_ARCHIVE }}
          gh release upload ${{ github.ref_name  }} ${{ steps.compile2.outputs.BUILT_CHECKSUM }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish --allow-dirty
        env:
            CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
