# name: "Release"

# on:
#   push:
#     tags:
#       - "v*.*.*"

# jobs:
#   release:
#     name: Release ${{ matrix.target }} ${{ matrix.archive }}
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - target: x86_64-unknown-linux-musl
#             archive: tar.gz tar.xz
#           - target: x86_64-apple-darwin
#             archive: tar.gz zip
#     steps:
#       - uses: actions/checkout@v4
#       - name: Compile and release
#         uses: rust-build/rust-build.action@v1.4.4
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           RUSTTARGET: ${{ matrix.target }}
#           ARCHIVE_TYPES: ${{ matrix.archive }}

#   publish:
#     name: Publish to crates.io
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions-rust-lang/setup-rust-toolchain@v1
#       - run: |
#           cargo publish --allow-dirty
