name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Cargo check
      run: cargo check --all-features
    - name: Commit Cargo.lock
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Cargo.lock
        git commit -m "chore: update Cargo.lock"
        git push
